In [1]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://test:"+"test1"+"@14.49.45.15:3306/sumin?charset=utf8",
                        encoding='utf-8')

QUERY = """
    select *
    from basic_data;
"""
df = pd.read_sql(QUERY, engine)
df.tail()

,game_id,summoner_id,team_position,game_result,champion,spell_1,spell_2,kill,death,assist,lane,cs,ban_champion
995,4502195435,8-RhP9xHeiozXZuIY8JYY42Qb3HcuWfxGIFU7K2BkMsCOSQ,200,0,10,12,4,0,3,0,1,55,81
996,4502195435,kif6lkSeZf57A-6Ye9awx3KnLvnO4QnRVDo_hg63ffyTOwg,200,0,245,14,4,1,3,0,2,126,-1
997,4502195435,bqTuupnGTDUFYACYji6TtytIdX9Yo-zViuELMh30VZUOAts,200,0,64,11,4,3,6,0,3,20,104
998,4502195435,Y_0MMNxI6LHOdXj4egUcEWiv2yQm5Gr06AE0E4U9FUOJ7Nw,200,0,523,7,4,0,3,0,4,55,157
999,4502195435,q74Pmw_Kxj5FTZ47mXH4PKKU8_aNfZyuxswdrm0z5h24nlA,200,0,350,14,3,0,3,2,5,0,-1

In [2]:
df

,game_id,summoner_id,team_position,game_result,champion,spell_1,spell_2,kill,death,assist,lane,cs,ban_champion
0,4562950701,KhbgPtAzVMy4RS_J5B4tsPB3qNiiFw1I4NOutKG79dIeon1a,100,1,86,4,14,4,4,4,1,72,555
1,4562950701,jW77Q1aNEFIyBnUgeRsYRnLXe0oGuRf3JG8AXTFkTBvUhw,100,1,30,11,4,13,5,15,2,62,122
2,4562950701,FM3238G3cZfdfw1A_VrRhoo6c3qd_VpBGxQaxDS4vUPjsic,100,1,75,6,7,11,3,8,3,130,111
3,4562950701,4vexJv8ISxAQbRIiSOeVxGNuUKozWBRv0N6sjaUAJ56lrA,100,1,51,7,4,4,7,16,4,150,64
4,4562950701,pdHOCeN0NtWZyPaBrIaY8UifzT0H0QSN7VBNVB36SNsC1A,100,1,25,14,4,0,8,14,5,10,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,4502195435,8-RhP9xHeiozXZuIY8JYY42Qb3HcuWfxGIFU7K2BkMsCOSQ,200,0,10,12,4,0,3,0,1,55,81
996,4502195435,kif6lkSeZf57A-6Ye9awx3KnLvnO4QnRVDo_hg63ffyTOwg,200,0,245,14,4,1,3,0,2,126,-1
997,4502195435,bqTuupnGTDUFYACYji6TtytIdX9Yo-zViuELMh30VZUOAts,200,0,64,11,4,3,6,0,3,20,104
998,4502195435,Y_0MMNxI6LHOdXj4egUcEWiv2yQm5Gr06AE0E4U9FUOJ7Nw,200,0,523,7,4,0,3,0,4,55,157
999,4502195435,q74Pmw_Kxj5FTZ47mXH4PKKU8_aNfZyuxswdrm0z5h24nlA,200,0,350,14,3,0,3,2,5,0,-1

In [3]:
import urllib.request, json 
with urllib.request.urlopen("http://ddragon.leagueoflegends.com/cdn/10.15.1/data/en_US/champion.json") as url:
    champ_data = json.loads(url.read().decode())

In [9]:
champ_dic

{'266': 'Aatrox',
 '103': 'Ahri',
 '84': 'Akali',
 '12': 'Alistar',
 '32': 'Amumu',
 '34': 'Anivia',
 '1': 'Annie',
 '523': 'Aphelios',
 '22': 'Ashe',
 '136': 'AurelionSol',
 '268': 'Azir',
 '432': 'Bard',
 '53': 'Blitzcrank',
 '63': 'Brand',
 '201': 'Braum',
 '51': 'Caitlyn',
 '164': 'Camille',
 '69': 'Cassiopeia',
 '31': 'Chogath',
 '42': 'Corki',
 '122': 'Darius',
 '131': 'Diana',
 '119': 'Draven',
 '36': 'DrMundo',
 '245': 'Ekko',
 '60': 'Elise',
 '28': 'Evelynn',
 '81': 'Ezreal',
 '9': 'Fiddlesticks',
 '114': 'Fiora',
 '105': 'Fizz',
 '3': 'Galio',
 '41': 'Gangplank',
 '86': 'Garen',
 '150': 'Gnar',
 '79': 'Gragas',
 '104': 'Graves',
 '120': 'Hecarim',
 '74': 'Heimerdinger',
 '420': 'Illaoi',
 '39': 'Irelia',
 '427': 'Ivern',
 '40': 'Janna',
 '59': 'JarvanIV',
 '24': 'Jax',
 '126': 'Jayce',
 '202': 'Jhin',
 '222': 'Jinx',
 '145': 'Kaisa',
 '429': 'Kalista',
 '43': 'Karma',
 '30': 'Karthus',
 '38': 'Kassadin',
 '55': 'Katarina',
 '10': 'Kayle',
 '141': 'Kayn',
 '85': 'Kennen',
 '121': 'Khazix',
 '203': 'Kindred',
 '240': 'Kled',
 '96': 'KogMaw',
 '7': 'Leblanc',
 '64': 'LeeSin',
 '89': 'Leona',
 '876': 'Lillia',
 '127': 'Lissandra',
 '236': 'Lucian',
 '117': 'Lulu',
 '99': 'Lux',
 '54': 'Malphite',
 '90': 'Malzahar',
 '57': 'Maokai',
 '11': 'MasterYi',
 '21': 'MissFortune',
 '62': 'MonkeyKing',
 '82': 'Mordekaiser',
 '25': 'Morgana',
 '267': 'Nami',
 '75': 'Nasus',
 '111': 'Nautilus',
 '518': 'Neeko',
 '76': 'Nidalee',
 '56': 'Nocturne',
 '20': 'Nunu',
 '2': 'Olaf',
 '61': 'Orianna',
 '516': 'Ornn',
 '80': 'Pantheon',
 '78': 'Poppy',
 '555': 'Pyke',
 '246': 'Qiyana',
 '133': 'Quinn',
 '497': 'Rakan',
 '33': 'Rammus',
 '421': 'RekSai',
 '58': 'Renekton',
 '107': 'Rengar',
 '92': 'Riven',
 '68': 'Rumble',
 '13': 'Ryze',
 '113': 'Sejuani',
 '235': 'Senna',
 '875': 'Sett',
 '35': 'Shaco',
 '98': 'Shen',
 '102': 'Shyvana',
 '27': 'Singed',
 '14': 'Sion',
 '15': 'Sivir',
 '72': 'Skarner',
 '37': 'Sona',
 '16': 'Soraka',
 '50': 'Swain',
 '517': 'Sylas',
 '134': 'Syndra',
 '223': 'TahmKench',
 '163': 'Taliyah',
 '91': 'Talon',
 '44': 'Taric',
 '17': 'Teemo',
 '412': 'Thresh',
 '18': 'Tristana',
 '48': 'Trundle',
 '23': 'Tryndamere',
 '4': 'TwistedFate',
 '29': 'Twitch',
 '77': 'Udyr',
 '6': 'Urgot',
 '110': 'Varus',
 '67': 'Vayne',
 '45': 'Veigar',
 '161': 'Velkoz',
 '254': 'Vi',
 '112': 'Viktor',
 '8': 'Vladimir',
 '106': 'Volibear',
 '19': 'Warwick',
 '498': 'Xayah',
 '101': 'Xerath',
 '5': 'XinZhao',
 '157': 'Yasuo',
 '83': 'Yorick',
 '350': 'Yuumi',
 '154': 'Zac',
 '238': 'Zed',
 '115': 'Ziggs',
 '26': 'Zilean',
 '142': 'Zoe',
 '143': 'Zyra'}

In [42]:
ban_top_10 = df.groupby('ban_champion').count()['summoner_id'].sort_values()[::-1].index[:11].tolist()

In [43]:
[champ_dic[str(i)] for i in ban_top_5[1:]]

['Nautilus',
 'Zed',
 'Yasuo',
 'LeeSin',
 'Blitzcrank',
 'Morgana',
 'Caitlyn',
 'Sylas',
 'Leblanc']

In [44]:
picl_top_10 = df.groupby('champion').count()['summoner_id'].sort_values()[::-1].index[:11].tolist()

In [45]:
[champ_dic[str(i)] for i in picl_top_10[1:]]

['Caitlyn',
 'LeeSin',
 'Ashe',
 'Ekko',
 'Yasuo',
 'Malphite',
 'Zed',
 'Graves',
 'Yuumi',
 'Varus']